= SimpleBot Documentation
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
:pdf-page-size: Letter
:toc: right
:toc-title: Table of Contents
:toclevels: 4
:imagesdir: ./

== Overview

SimpleBot is a simple chat bot engine for the Unity platform. Given input sentences, SimpleBot detects the intent and then reply the reply sentence.
Simple bot provide Amazon Echo style JSON configuration. In addition, functions for practical applications such as state transitions or slot type matching are provided.

== Basic Usage

SimpleBot has `Simple.BotEngine` which manages the dialogue with the user following specified configuration.file. We can create a `BotEngine` specifing the configuration file.

```
private void createBot()
{
    string settingFilePath = Application.dataPath + "/SimpleBot/Scenes/simple-bot-conf.json";
    string setting = File.ReadAllText(settingFilePath);
    ConfigurationLoader configurationLoader = new ConfigurationLoader();
    Configuration config = configurationLoader.loadFromString(setting);
    this.bot = new BotEngine(config);
}
```

After we create a `BotEngine` instance, the instance is ready to get input sentence.

```
public void RespondtoInput()
{
    var input = inputField.text;
    var reply = this.bot.replySentence(input);
    text.text = reply;
    inputField.text = "";
}
```

In the following sections, we learn the configurations and practical usage.

== Configurations

SimpleBot has a JSON formatted confiuration file. The following is a tiny example.

```
{
  "intents": [
    {
      "name": "repeat",
      "match": {
        "type": "verbatim",
        "expressions": [ "repeat", "pardon me?" ]
      }
    }
  ],
  "responders":
  {
    "repeat": [
      {
	"responds": [ "Go stragiht." ],
      }
    ],
    "default": [{
      "target": "default",
      "responds": [ "Sorry I do not understand what you mean." ]
    }]
  }
}
```

In the above example, Configuration files have two blocks (`intents` and `responders`).
We register `intents` to extract intent from input sentences. `responders` specify the handlers to output the reply sentences for target intents.

### Intent settings

#### Slot

#### Condition

### Responder settings

#### Effect

## Classes

## Samples

### Guide
