= SimpleBot Documentation
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
:pdf-page-size: Letter
:toc: right
:toc-title: Table of Contents
:toclevels: 4
:imagesdir: ./

== Overview

SimpleBot is a simple chat bot engine for the Unity platform. Given input sentences, SimpleBot detects the intent and then reply the reply sentence.

* Amazon Echo style simple configuration (JSON)
* Provide functions useful for builing practical application
  * slot and types
  * state transitions with effect of getting an intent
  * can make chage the reoponds with the user's status

== Basic Example

SimpleBot has `Simple.BotEngine` which manages the dialogue with the user following specified configuration.file.


== Configurations

SimpleBot has a JSON formatted confiuration file. The following is a tiny example.

```
{
  "intents": [
    {
      "name": "repeat",
      "match": {
        "type": "verbatim",
        "expressions": [ "repeat", "pardon me?" ]
      }
    }
  ],
  "responders":
  {
    "repeat": [
      {
	"responds": [ "Go stragiht." ],
      }
    ],
    "default": [{
      "target": "default",
      "responds": [ "Sorry I do not understand what you mean." ]
    }]
  }
}
```

In the above example, Configuration files have two blocks (`intents` and `responders`).
We register `intents` to extract intent from input sentences. `responders` specify the handlers to output the reply sentences for target intents.

### Intent settings

#### Slot

#### Condition

### Responder settings

#### Effect

## Classes

## Samples

### Guide